import os
import qrcode
from PIL import Image, ImageDraw, ImageEnhance
import numpy as np

# Set Hugging Face cache to F drive
os.environ["HF_HOME"] = "F:\\huggingface_cache"
os.environ["HF_HUB_CACHE"] = "F:\\huggingface_cache\\hub"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "300"

def create_qr_code(data, size=512, border=4):
    """Create a QR code with specified size"""
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,  # High error correction
        box_size=10,
        border=border,
    )
    qr.add_data(data)
    qr.make(fit=True)
    
    # Create QR code image with high contrast
    qr_img = qr.make_image(fill_color="black", back_color="white")
    # Resize to desired size
    qr_img = qr_img.resize((size, size), Image.Resampling.LANCZOS)
    return qr_img

def make_image_qr_code(base_image, qr_image):
    """
    Make the image itself BE a scannable QR code
    The QR code pattern is integrated into the image while maintaining scannability
    
    Args:
        base_image: PIL Image - The generated image
        qr_image: PIL Image - The QR code pattern (black and white)
    
    Returns:
        PIL Image - The image styled as a QR code
    """
    # Convert to RGB if needed
    if base_image.mode != 'RGB':
        base_image = base_image.convert('RGB')
    if qr_image.mode != 'RGB':
        qr_image = qr_image.convert('RGB')
    
    # Resize both to same size
    target_size = max(base_image.size)
    base_image = base_image.resize((target_size, target_size), Image.Resampling.LANCZOS)
    qr_image = qr_image.resize((target_size, target_size), Image.Resampling.LANCZOS)
    
    # Convert to numpy arrays for processing
    base_array = np.array(base_image)
    qr_array = np.array(qr_image)
    
    # Convert QR code to grayscale mask (0-255)
    qr_gray = np.dot(qr_array[...,:3], [0.2989, 0.5870, 0.1140])
    
    # Normalize QR mask to 0-1 (where 1 is white/background, 0 is black/data)
    qr_mask = qr_gray / 255.0
    
    # Create subtle QR code where IMAGE is the main focus:
    # - Image remains prominent and beautiful
    # - QR code is very subtle in background (like reference.jfif)
    # - Still scannable but image takes priority
    
    # Very subtle factors - image is main, QR is barely visible background
    dark_factor = 0.92  # Very slight darkening for QR data areas
    light_factor = 1.08  # Very slight lightening for QR background areas
    
    # Apply the mask: very subtle adjustments to preserve image beauty
    result_array = base_array.copy().astype(float)
    
    # Expand mask to 3D for RGB channels
    qr_mask_3d = np.expand_dims(qr_mask, axis=2)
    
    # For black QR areas (qr_mask close to 0), very slightly darken
    dark_mask = (1 - qr_mask_3d)  # Inverted: 1 where QR is black
    result_array = result_array * (1 - dark_mask * (1 - dark_factor))
    
    # For white QR areas (qr_mask close to 1), very slightly lighten
    light_mask = qr_mask_3d  # 1 where QR is white
    result_array = result_array * (1 + light_mask * (light_factor - 1))
    
    # Add minimal contrast adjustment to maintain scannability
    # This ensures QR is readable while image stays beautiful
    contrast_boost = 0.05  # Very small boost
    qr_contrast = (qr_mask_3d - 0.5) * 2  # -1 to 1 range
    result_array = result_array + (qr_contrast * contrast_boost * 30)
    
    # Ensure values are in valid range
    result_array = np.clip(result_array, 0, 255).astype(np.uint8)
    
    # Convert back to PIL Image
    result_image = Image.fromarray(result_array)
    
    return result_image

# Configuration
QR_DATA = "Soykot Podder(Senior Ai Engineer)(Indian Institute of Information Technology)(IIIT)"  # Change this to your desired URL or text
INPUT_IMAGE = "output3.png"  # Image generated by text_to_image.py
OUTPUT_FILE = "qr_output.png"

# Check if input image exists
if not os.path.exists(INPUT_IMAGE):
    print(f"Error: Input image '{INPUT_IMAGE}' not found!")
    print("Please run 'text_to_image.py' first to generate the image.")
    print("Or change INPUT_IMAGE to point to an existing image file.")
    exit(1)

# Generate QR code
print(f"Creating QR code with data: {QR_DATA}")
qr_img = create_qr_code(QR_DATA, size=512)

# Load existing image
print(f"\nLoading image from: {INPUT_IMAGE}")
generated_image = Image.open(INPUT_IMAGE)
print(f"Image loaded: {generated_image.size[0]}x{generated_image.size[1]}")

# Make the image itself BE a QR code
print("\nConverting image to QR code format (artistic QR code)...")
final_image = make_image_qr_code(generated_image, qr_img)

# Save the result
final_image.save(OUTPUT_FILE)
print(f"\nArtistic QR code image saved to: {OUTPUT_FILE}")
print(f"QR code data: {QR_DATA}")
print("The entire image IS the QR code - try scanning it!")

